name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install
    
    - name: install --save-dev jest
      run: npm install --save-dev jest @testing-library/react @testing-library/jest-dom

    - name: Run the tests and generate coverage report
      run: npm test -- --coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4

    - name: Build
      run: npm run build

    - name: Deploy
      run: |
        git config --global user.name $user_name
        git config --global user.email $user_email
        git remote set-url origin https://${github_token}@github.com/${repository}
        npm run deploy
        
      env:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.GH_TOKEN }}
        repository: ${{ github.repository }}

        uses: peaceiris/actions-gh-pages@v4
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./dist  # Replace with your build output directory
          publish_branch: gh-pages

    - name: Zip the build directory
      run: zip -r web-app.zip dist

    - name: Install jq
      run: sudo apt-get install jq

  Deploy_To_AppCenter:
    needs: [build]
    runs-on: ubuntu-latest
    env:
      APP_CENTER_API_TOKEN: ${{ secrets.APP_CENTER_API_TOKEN }}
      APP_OWNER_NAME: danial.mohemmed  # Replace with your App Center owner name
      APP_NAME: React2  # Replace with your App Center application name
      DEPLOYMENT_NAME: Production  # Replace with your deployment name in App Center
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload and Deploy to App Center
        run: |
          echo "Creating release in App Center..."
          
          # Initiate a release upload
          upload_response=$(curl -X POST \
            -H "Content-Type: application/json" \
            -H "X-API-Token: $APP_CENTER_API_TOKEN" \
            https://api.appcenter.ms/v0.1/apps/$APP_OWNER_NAME/$APP_NAME/release_uploads)

          echo "Upload response: $upload_response"

          upload_id=$(echo $upload_response | jq -r '.upload_id')
          upload_url=$(echo $upload_response | jq -r '.upload_url')

          echo "Upload ID: $upload_id"
          echo "Upload URL: $upload_url"

          if [ -z "$upload_id" ] || [ -z "$upload_url" ]; then
            echo "Error: upload_id or upload_url is empty"
            exit 1
          fi

          # Upload the zip file
          upload_status=$(curl -T web-app.zip -H "Content-Type: application/zip" "$upload_url")

          echo "Upload status: $upload_status"

          # Commit the release upload
          commit_response=$(curl -X PATCH \
            -H "Content-Type: application/json" \
            -H "X-API-Token: $APP_CENTER_API_TOKEN" \
            -d '{"status": "committed"}' \
            https://api.appcenter.ms/v0.1/apps/$APP_OWNER_NAME/$APP_NAME/release_uploads/$upload_id)

          echo "Commit response: $commit_response"

          release_id=$(echo $commit_response | jq -r '.release_id')

          echo "Release ID: $release_id"

          if [ -z "$release_id" ]; then
            echo "Error: release_id is empty"
            exit 1
          fi

          # Update release with release notes and distribute to deployment
          update_response=$(curl -X PATCH \
            -H "Content-Type: application/json" \
            -H "X-API-Token: $APP_CENTER_API_TOKEN" \
            -d "{\"release_notes\": \"New version of the web app\"}" \
            https://api.appcenter.ms/v0.1/apps/$APP_OWNER_NAME/$APP_NAME/releases/$release_id)

          echo "Update response: $update_response"

          # Distribute the release
          distribute_response=$(curl -X POST \
            -H "Content-Type: application/json" \
            -H "X-API-Token: $APP_CENTER_API_TOKEN" \
            -d "{\"id\": \"$release_id\"}" \
            https://api.appcenter.ms/v0.1/apps/$APP_OWNER_NAME/$APP_NAME/deployments/$DEPLOYMENT_NAME/releases)

          echo "Distribute response: $distribute_response"

          echo "Release created successfully in App Center with ID: $release_id"
