name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: install --save-dev jest
      run: npm install --save-dev jest @testing-library/react @testing-library/jest-dom

    - name: Run the tests and generate coverage report
      run: npm test -- --coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4

    - name: Build
      run: npm run build

    - name: Deploy
      run: |
        git config --global user.name $user_name
        git config --global user.email $user_email
        git remote set-url origin https://${github_token}@github.com/${repository}
        npm run deploy
        
      env:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.GH_TOKEN }}
        repository: ${{ github.repository }}

        uses: peaceiris/actions-gh-pages@v4
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./dist  # Replace with your build output directory
          publish_branch: gh-pages

  deploy_to_appcenter:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Deploy to App Center
        env:
          APPCENTER_SECRET: ${{ secrets.APPCENTER_SECRET }}
        run: |
          curl -X POST -d '{"release_notes":"New version"}' -H "Content-Type: application/json" -H "X-API-Token: $APPCENTER_SECRET" https://api.appcenter.ms/v0.1/apps/daniel.mohammed/React2/releases
